In [7]:
import numpy as np

In [8]:
arr1 = np.array( [1,2,3]  )
print (arr1)
# 整数型数组打印出来间隔为空格

[1 2 3]


In [9]:
arr2 = np.array([1.0,2,4])
print(arr2)
#浮点型数组打印出来间隔为点
#同化定理：整数型数组插入浮点数，该浮点数会变成整数，数组仍为整型。浮点型插入整形同理。

[1. 2. 4.]


In [10]:
arr3 = arr1.astype(float)
print(arr3)
#如需进行两种类型数组的转化要用到astype方法。注意！array为类，arr1为它的一个实例
#我们对arr1这个实例用array里面的函数astype，这个astype就叫方法
#粗暴点，接在变量后的为方法
#还记得前文提到过的整型数组和浮点型数组打印的差别吗？观察以下结果，可以发现调用astype后数组型式转化了。

[1. 2. 3.]


In [15]:
print( arr1 + 0.0)
print( arr1*1.0  )
#整数数组与浮点数进行运算变为浮点型
print(arr1 / 1)
#整数数组除以一个数时，哪怕是除以整数，也会变为浮点型数组
print(arr1 +arr2)
#整数与浮点型进行加减运算时候，也会变为浮点型。
#运算时，整数经常会升级为浮点型，会增加内存，但不会影响计算。而浮点型一般不会变为整数型

[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]
[2. 4. 7.]


In [20]:
arr4 = np.ones(3)
print(arr4)
#代表有三列的一维数组
arr5 = np.ones((1,3))
#代表，创立一个1行三列的二维数组
#注意！二维两层括号，三维类推
print(arr4.shape)
print(arr5.shape)

[1. 1. 1.]
(3,)
(1, 3)


In [23]:
#一维数组和二维数组之间的转化均要使用数组的重塑方法.reshape，需传入重塑后的形状参数
#给定一个参数后，另一个可以写负1，让计算机自己去算另一个参数为多少
arr6 = np.arange(10)
print(arr6)
arr7 = arr6.reshape((1,-1))
print(arr7)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
