In [2]:
import numpy as np
#（1）访问数组切片
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#从 x 切到 y的几种解法(中间用冒号)
#注意！切片这里的索引不太一样。对应位置：  （0）a （1）b （2）c。简单理解第几个元素就代表它和它之前
print(arr1[1:4])
#从x切到y
print(arr1[1:])
#第二个空着代表切到末尾
print(arr1[:5])
#第一个空着代表从头切到y


[1 2 3]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [7]:
#带负号的情况
print(arr1[2:-2])
#切除开头和结尾两个

[2 3 4 5 6 7]


In [8]:
#隔几个元素切
print(arr1[ : :2])
#每隔两个元素采样
print(arr1[1:-2:2])
#注意！有负数率代表切除，切掉，不要了！本例先切除对应元素。再每隔两个元素取样

[0 2 4 6 8]
[1 3 5 7]


In [10]:
#（2）接下来是访问矩阵切片
arr2 = np.arange(0,20).reshape(4,5)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
print(arr2[1:3,1:-1])
#先取一到三行，再把第一列和最后一列切除不要！

[[ 6  7  8]
 [11 12 13]]


In [12]:
#跳跃采样
print(arr2[::3,::2])
#每隔几行几列取。这里的索引注意从o开始，对应的是第一行元素之前。详看之前

[[ 0  2  4]
 [15 17 19]]


In [17]:
#(3)提取矩阵的行
print(arr2)
print("result：")
print(arr2[2,:])
#提取第二行

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
result：
[10 11 12 13 14]


In [18]:
#提取一到二行，因为区间是左闭右开
#最好不要简写成arr[2]
print(arr2[1:3,])
#观察结果的括号数量，会发现输出的是一个矩阵。

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
#(4)提取列向量
print(arr2[:,2])
#提取第二列，观察结果可发现结果是向量！！！

[ 2  7 12 17]


In [26]:
print(arr2[:,1:3])
#提取一到2列，左闭右开

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]


In [29]:
#(4)数组切片仅是视图。意思书Numpy的切片不会创建新变量
#但也可以使用copy创建拷贝切片
copy = arr1[:4].copy()
print(copy)
print(arr1)

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#(5)数组赋值仅是绑定
#换言之，numpy的数组赋值不会创建新的变量
