In [11]:
#本小节主要介绍数组的索引
#输入正数正着访问，负数倒着访问
import numpy as np
arr1 = np.arange( 1,10 )
print(arr1[3])
print(arr1[-4])

4
6


In [20]:
#修改数组元素，例如插入103到第三个位置
#4变为103
arr1[3] = 103;
print(arr1)

[  1   2   3 103   5   6   7   8   9]


In [24]:
#访问矩阵
#回忆：两个中括号代表行矩阵
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [28]:
#访问时，例如想访问第0行第二列
#用一个中括号，用逗号区分行和列：
print(arr2[1,0])
print(arr2[1,1])
print(arr2[1,2])
print(arr2[0,2])
print(arr2[0,1])
print(arr2[0,0])

4
5
6
3
2
1


In [29]:
#修改元素时，直接修改就行。
arr2[1,0] = 130.9;
print(arr2)
#回忆：本例130.9为浮点型，插入整数型数组时发生截断

[[  1   2   3]
 [130   5   6]]


In [37]:
#接下来介绍花式索引（Fancy indexing）
#刚刚介绍时候，使用arr1[x]和arr1[x,y]形式分别访问向量和行矩阵
#上述，逗号用于区分行和列，接下来的逗号将额外新增一个功能
#对于向量，花式索引会提取对饮位置的元素
arr3 = np.arange(0,90,10)
print(arr3)
print("使用花式索引访问，访问结果：")
print(arr3[[0,2]])
print(arr3[[0,2,3,6,7]])


[ 0 10 20 30 40 50 60 70 80]
使用花式索引访问，访问结果：
[ 0 20]
[ 0 20 30 60 70]


In [45]:
#对于行矩阵，最外层中括号里面的两个中括号，第一个中括号为行数，第二个为列数
#每次提取需两个括号里的元素配合例如
arr3 = np.arange(1,29).reshape(7,-1)
print(arr3)
#回忆：使用reshape可用-1代表自动计算维度。

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]]


In [48]:
#使用花式索引提取矩阵元素：
print(arr3[[0,1,2,3],[0,1,2,3]])

[ 1  6 11 16]


In [ ]:
#总结一下：
#索引方式     向量                     矩阵                                     区别
#普通索引    arr[x]                  arr[x,y]                                一个括号
#花式索引    arr[[x,y,z...]]       arr[[x1,x2,x3...]   [y1,y2,y3...]]        两个括号
# 花式索引的输出为向量（就是带着一个中括号）