In [1]:
import numpy as np
#数组的变形
#（1）使用.T转置
#数组的转置方法为.T因此遇到向量要先将其转为矩阵，矩阵也可
arr1 = np.arange(1,4)
print(arr1)
arr2 = arr1.reshape((1,-1))
arr3 = arr2.T
print(arr2)
print(arr3)

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [9]:
#（2）使用concatenate拼接数组或者向量
arr_2 = np.array([1,2,3])
arr_3 = np.array([4,5,6])
arr4  =np.concatenate([arr_2,arr_3]) 
print(arr4)

[1 2 3 4 5 6]


In [7]:
#拼接时要注意维度
#concatenate默认axis为0，可修改为1按列拼接，按行拼接
#向量和矩阵不能拼接
arr_4 = np.concatenate([arr_2,arr_3])
print(arr_4)

[1 2 3 4 5 6]


In [12]:
#（3）向量的分裂
#使用np.split对向量进行分裂
arr = np.arange(10,100,10)
print(arr)
arr_9,arr_10,arr_11 = np.split(arr,[2,8])
print(arr_9)
print(arr_10)
print(arr_11)
#2和8的意思是从第二和第八出砍两刀

[10 20 30 40 50 60 70 80 90]
[10 20]
[30 40 50 60 70 80]
[90]


In [14]:
#（4）矩阵的分裂
ar_r = np.arange(1,9).reshape(2,4)
print(ar_r)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
#按行分裂，[1]代表从第一行处分开
ar_r1,ar_r2 = np.split(ar_r,[1])
print(ar_r1,"\n\n",ar_r2)

[[1 2 3 4]] 

 [[5 6 7 8]]


In [ ]:
#按裂分开
a,b,c = np.split(ar_r,[1,3],axis=1)
print(a,"\n",b,"\n",)