In [1]:
import numpy as np

In [2]:
#创建一维数组--向量
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [3]:
#创建二维数组--行矩阵
arr2 = np.array([[1,2,3]])
print(arr2)

[[1 2 3]]


In [5]:
#创建二维数组--列矩阵
arr3 = np.array([[1],[2],[3]])
print(arr3)


[[1]
 [2]
 [3]]


In [6]:
#使用arange创建递增数组
#只传入一个参数，打印从0到n
arr4 = np.arange(10)
print(arr4)


[0 1 2 3 4 5 6 7 8 9]


In [7]:
#传入两个参数打印n1到n2
arr5 = np.arange(10,20)
print(arr5)

[10 11 12 13 14 15 16 17 18 19]


In [9]:
#传入三个参数，从n1开始，到n2结束，步长为n3
arr6 = np.arange(1,33,4)
print(arr6)

[ 1  5  9 13 17 21 25 29]


In [15]:
#使用np.zeros()函数以及np.ones()函数创建同值数组
#对于，zeros（）只传入一个数字，返回一个向量。
arr_1 = np.zeros(3)
print (arr_1)
#传入行矩阵,不同之处要用括号括起来：
arr_2 = np.ones((1,3))
print(arr_2)
#全一数组同理
#具体的可以用np.ones创建形状在在前面乘以数字
arr_3 = 3.14 * np.ones((1,3))
print(arr_3)

[0. 0. 0.]
[[1. 1. 1.]]
[[3.14 3.14 3.14]]


In [19]:
#使用np.random创建随机数组
#该系列函数很多，主要讲解四个
#第一个random：创建0-1均匀分布的浮点型随机数组。
#下式第一个random代表np中的模块random，第二个random代表模块random中的函数，5代表形状为5的向量。
arr_3 = np.random.random(5)
print(arr_3)

[0.4337533  0.75863431 0.13680397 0.03571165 0.99588104]
[[0.18512752 0.72454407 0.9629952  0.70163734 0.03468652 0.64696821
  0.39514674 0.2827326  0.15653347]
 [0.46659381 0.81759463 0.09091336 0.28969993 0.69589906 0.76633527
  0.82061047 0.33437362 0.66595588]]


In [21]:
#也可以生产几行几列的矩阵例如：
arr_4 = np.random.random((2,9))
print(arr_4)

[[0.09843242 0.27206989 0.97303979 0.83883583 0.24592059 0.11244018
  0.11680273 0.83041602 0.54534731]
 [0.61097525 0.06537496 0.21437876 0.45083195 0.12958399 0.07023814
  0.65284319 0.61600019 0.81240353]]


In [22]:
#该函数并非只能创建0-1.例如：
#如果想创建60-100范围内均匀分布的3行3列随机数组，可输入：
arr_5 = 40*np.random.random((3,5))+60;
print(arr_5)

[[69.55558081 63.86655187 68.86765158 74.50800678 97.63472221]
 [67.12517109 75.72766924 99.69303534 79.45808409 98.36218019]
 [91.34183594 93.88895331 84.72414139 63.01752272 66.02586639]]


In [23]:
#第二个randint：创建整数型随机数组
#随机生产一个
arr_6 = np.random.randint(10,100)
print(arr_6)

49


In [27]:
#也可以好几个，也可以矩阵,形状有第三个参数决定
arr_7 = np.random.randint(10,100,4)
arr_8 = np.random.randint(10,100,(3,6))
print(arr_7)
print(arr_8)

[79 40 76 69]
[[27 29 36 59 63 73]
 [15 95 84 89 63 77]
 [74 59 67 21 69 91]]


In [28]:
#第三个：使用normal创建服从正态分布的随机数组,第三个依旧形状，不赘述
arr_9 = np.random.normal(0,1,9)
#本例中均值为0，标准差为1，可直接使用np.random.randn实现
#normal可以指定均值和标准差，默认为0
print(arr_9)

[-1.63565175 -0.25842025  0.41018185 -0.79023312 -0.41629395  0.12113629
  0.31849743  1.20101365  0.9810323 ]
